# Site settings
title: Emanuela Kuhlman
email: emanuelakuhlman@outlook.de
url: http://localhost:4000
#baseurl: /
description: :)
phone: xxx
keywords: Jekyll, Template, Website, Resume, Portfolio, Personal, CV
meta_author: Emanuela Kuhlman

markdown: xxx
permalink: pretty