# Site settings
title: Emanuela
email: emanuelakuhlman@outlook.de
url: http://localhost:4000
#baseurl: /
description: :)
phone: xxx
keywords: Jekyll, Template, Website, Resume, Portfolio, Personal, CV
meta_author: xxx

markdown: xxx
permalink: pretty