# Site settings
title: Emanuela Kuhlman
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Emanuela Kuhlman
user_description: I'm a Data Scientist.
user_title: Data Scientist
email: emanuelakuhlman@outlook.de
# twitter_username: lorem_ipsum
#instagram_username: lorem_ipsum
#facebook_username: lorem_ipsum
linkedin_username: emamarela
github_username:  emamarela
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
